language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - COVERAGE=no
    - DB=mysql
    - RELEASE=stable

matrix:
  include:
    - php: 7.2
    - php: 7.2
      env: RELEASE=lowest
    - php: 7.3
      env: COVERAGE=yes
    - php: 7.3
      env: COVERAGE=yes DB=pgsql
    - php: 7.3
      env: COVERAGE=yes DB=sqlite

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - COMPOSER_FLAGS=$([ $RELEASE == "lowest" ] && echo "--prefer-lowest" || echo "")
  - PHPUNIT_FLAGS=$([ $COVERAGE == "yes" ] && echo "--coverage-clover=coverage.xml" || echo "")

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable $COMPOSER_FLAGS

before_script:
  - cp tests/config/database.travis.php tests/config/database.php
  - |
    if [ $DB == "mysql" ]; then
      wget https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
      sudo dpkg -i mysql-apt-config_0.8.12-1_all.deb
      sudo apt-get update
      sudo apt-get install -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
      sudo systemctl restart mysql
    fi
  - mysql -e 'create database `test`;'
  - psql -c 'create database "test";' -U postgres

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - |
    if [ $COVERAGE == "yes" ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi